// Test generated by RoostGPT for test roost-test using AI Model gpt

package main

import (
	"encoding/json"
	"log"
	"net"
	"net/http"
	"sort"
	"sync"
	"testing"
)

var port = "8080" // TODO: Change the port number if required

func serveRoot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("Hello, world!"))
}

func TestMain0557973ac7(t *testing.T) {
	go main()

	resp, err := http.Get("http://localhost:" + port)
	if err != nil {
		t.Error("Failed to connect to the server:", err)
	}

	if resp.StatusCode != http.StatusOK {
		t.Errorf("Expected status code %d, got %d", http.StatusOK, resp.StatusCode)
	}

	defer resp.Body.Close()
}

func TestServeRoot(t *testing.T) {
	req, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	rr := httptest.NewRecorder()
	handler := http.HandlerFunc(serveRoot)

	handler.ServeHTTP(rr, req)

	if status := rr.Code; status != http.StatusOK {
		t.Errorf("Expected status code %d, got %d", http.StatusOK, status)
	}

	expected := "Hello, world!"
	if rr.Body.String() != expected {
		t.Errorf("Expected response body %s, got %s", expected, rr.Body.String())
	}
}