# Test improved by RoostGPT for test test07Sept using AI Type Open AI and AI Model gpt-4

config:
  target: "{{ $processEnvironment.SERVER_URL }}"
  phases:
    - duration: 120
      arrivalRate: 40
  plugins:
    expect: {}
scenarios:
  - name: "Successful API request"
    flow:
      - get:
          url: "/products"
          expect:
            - statusCode: 200
            - hasProperty: "id"
            - hasProperty: "name"
            - hasProperty: "description"
            - hasProperty: "price"
            - hasProperty: "category"
            - hasProperty: "stock"
  - name: "API request with validation failure"
    flow:
      - get:
          url: "/invalid_url"
          expect:
            - statusCode: 404
  - name: "API request with edge case"
    flow:
      - get:
          url: "/products?name=@@@@@####"
          expect:
            - statusCode: 400
  - name: "API request for non-existing product"
    flow:
      - get:
          url: "/products?id=99999999"
          expect:
            - statusCode: 404
